config/routes.rb
GardenMemo::Application.routes.draw do

  # ルート
  root to: "top#index"

  # devise（ユーザ認証まわり）
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" }
  
  # トップページ
  get "top/index"

  # マイページ
  get "mypage/index"

  # 区画管理画面
  resource :section

  # 日誌画面
  resource :diary

  # 品種管理画面
  resource :plant

  # カレンダー詳細画面
  resource :calendar

  # 設定画面
  get "setting/index"

  # みんなのガーデン画面
  get "everyone_gardens/index"
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/diary.rb
class Diary < ActiveRecord::Base
end

app/models/layout.rb
class Layout < ActiveRecord::Base
end

app/models/plant.rb
class Plant < ActiveRecord::Base
end

app/models/public_setting.rb
class PublicSetting < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_auth.rb
class UserAuth < ActiveRecord::Base
end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @diary }
      else
        format.html { render action: 'new' }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_params
      params[:diary]
    end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plant }
      else
        format.html { render action: 'new' }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params[:plant]
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index

    # サインイン済みならマイページへリダイレクトする
    if user_signed_in? then
      redirect_to mypage_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/diaries/_form.html.erb
<%= form_for(@diary) do |f| %>
  <% if @diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% @diary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing diary</h1>

<%= render 'form' %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

app/views/diaries/index.html.erb
<h1>Listing diaries</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= link_to 'Show', diary %></td>
        <td><%= link_to 'Edit', edit_diary_path(diary) %></td>
        <td><%= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diary', new_diary_path %>

app/views/diaries/new.html.erb
<h1>New diary</h1>

<%= render 'form' %>

<%= link_to 'Back', diaries_path %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_diary_path(@diary) %> |
<%= link_to 'Back', diaries_path %>

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<h1>Listing plants</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>