config/routes.rb
GardenMemo::Application.routes.draw do

  # ルート
  root to: "top#index"

  # devise（ユーザ認証まわり）
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" }
  
  # トップページ
  get "top/index"

  # マイページ
  get "mypage/index"

  # 区画管理画面
  resource :section

  # 日誌画面
  resource :diary

  # 品種管理画面
  resource :plant

  # カレンダー詳細画面
  resource :calendar

  # 設定画面
  get "setting/index"

  # みんなのガーデン画面
  get "everyone_gardens/index"
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/diary.rb
class Diary < ActiveRecord::Base
end

app/models/layout.rb
class Layout < ActiveRecord::Base
end

app/models/plant.rb
class Plant < ActiveRecord::Base
end

app/models/public_setting.rb
class PublicSetting < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_auth.rb
class UserAuth < ActiveRecord::Base
end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plant }
      else
        format.html { render action: 'new' }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params[:plant]
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index

    # サインイン済みならマイページへリダイレクトする
    if user_signed_in? then
      redirect_to mypage_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/mypage/_menu.html.erb
<!-- メニュー(共通パーツ)-->
<div class="mypage-menu">
  <ul>
    <li><%= link_to "マイページ", mypage_index_path %></li>
    <li><%= link_to "予定を立てる", :controller => "calendars", :action => "show" %></li>
    <li><%= link_to "日誌をつける", new_diary_path %></li>
    <li><%= link_to "みんなのガーデン", everyone_gardens_index_path %></li>
    <li><%= link_to "品種管理", :controller => "plants", :action => "show" %></li>
    <li><%= link_to "設定", setting_index_path %></li>
    <li><%= link_to "ログアウト", destroy_user_session_path, :method => "delete" %></li>
  </ul>
</div>

app/views/mypage/index.html.erb
<!-- メニュー(共通パーツ)-->
<%= render 'menu' %>

<!-- お知らせ -->
<div class="mypage-announce">お知らせ</div>

<!-- プロフィール -->
<div class="mypage-profile">プロフィール</div>

<!-- 区画 -->
<div class="mypage-section">区画</div>

<!-- カレンダー -->
<div class="mypage-calendar">カレンダー</div>

<!-- 日誌 -->
<div class="mypage-diary">日誌</div>

app/views/top/index.html.erb
<!-- 背景 -->
<div class="toppage-background"></div>

<!-- メニュー -->
<div class="toppage-menu">
  <ul>
    <li><a href="#"></a></li>
    <li><a href="#"></a></li>
    <li><a href="#"></a></li>
    <li><a href="#"></a></li>
  </ul>
</div>

<!-- お知らせ -->
<div class="toppage-announce">
  おしらせ
</div>

<!-- ログイン -->
<div class="toppage-login">
  <%= link_to "ログイン", new_user_session_path %>
  <%= link_to "新規", new_user_registration_path %>
</div>

<!-- 紹介 -->
<div class="toppage-presentation">
  紹介
</div>